# Generated by Django 4.2.1 on 2023-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('department', models.CharField(choices=[('commerce', 'COMMERCE'), ('humanities', 'HUMANITIES'), ('science', 'SCIENCE')], max_length=10)),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('present', 'PRESENT'), ('absent', 'ABSENT')], max_length=7)),
            ],
        ),
    ]
